### ISSUE TITLE
Emoji not working

### ISSUE THREAD

**Issue by m3toh** [soeminnminn/SulfurKeyboard#1]
Hi

Emoji Not Working , If I click on the button emoji  , App Crashing Why ?

plez Help me

Thanx

**Comment by soeminnminn** [comment]
Hi m3toh,
   Emoji Keyboard is working fine. Source are not updated. 
https://play.google.com/store/apps/details?id=com.s16.inputmethod.skeyboard

Thank,

**Comment by m3toh** [comment]
Thank you it works
Please, Can you updated source code for Emoji Working 
I need him waiting for you 

 thank you very much

**Comment by soeminnminn** [comment]
### Not all updated.
